version: '3.0'

services:
    website-database:
        image: mysql:8.0.33
        container_name: website-database
        restart: always
        volumes:
            - data:/var/lib/mysql
            - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3308:3306
    website-api:
        image: website-api
        container_name: website-api
        restart: always
        volumes:
            - data:/var/lib/website-api
            - ./upload:/upload
        build:
          context: .
          dockerfile: src/Website.Api/Dockerfile
        ports:
            - 5000:5000
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
        depends_on:
            - website-database
volumes:
    data:
  