version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - website-mysql-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    ports:
      - 3308:3306
volumes:
  website-mysql-data: