name: Deloy to server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v3

        - name: send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: 1810814173
            token: 6085324979:AAGqsSjIngtpic5eTjUCJfzcYk6yeY0STdI
            message: |
              ${{ github.actor }} created commit:
              Commit message: ${{ github.event.commits[0].message }}
              
              Repository: ${{ github.repository }}
              
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
            file: ./src/Website.Api/Dockerfile

        - name: Connect to vps and run docker compose
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.HOST_IP }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            script: |
              cd /website-api/
              docker compose up -d

              