name: Build and Push to Docker

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v3
        - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --configuration Release --no-restore
        - name: Test
          run: dotnet test --no-restore --verbosity normal

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ngapham0705
            password: Aa@150297

        - name: Build and push Docker image
          env:
            DOCKER_USERNAME: ngapham0705
            DOCKER_REPOSITORY: website-api
            IMAGE_TAG: latest
          run: |
            docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG .
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG